### PR TITLE
feat: add webhook to apiland after publish

### PR DESCRIPTION
**Pull request by kitsonk**
I'm not 100% sure I added it all properly, but I think maybe I did.

The apiland auth token needs to be added to the repos secrets.  It is in the shared password vault as an API token.

### CODE REVIEW

**Comment by lucacasonato** [comment]
Looks good, but I need to fix CI before we can land this. Working on it in #286.

**Comment by lucacasonato** [comment]
Tests are failing because there is no apiland endpoint set up for testing. Could you fix this @kitsonk?

**Comment by kitsonk** [comment]
> Tests are failing because there is no apiland endpoint set up for testing. Could you fix this @kitsonk?

That was something I had a question about, what would be a good way to mock/create this?

**Comment by lucacasonato** [comment]
@kitsonk You could start a server during the test run and assert it gets the correct result?

**Comment by kitsonk** [comment]
> @kitsonk You could start a server during the test run and assert it gets the correct result?

🤦 I was having all this machinations in my head of how to figure out how to generate a docker image and terraform things... _sigh_. Silly me.

**Comment by kitsonk** [comment]
Ok @lucacasonato it took a bit, but a oneshot mock server seems to be working.

**Comment by kitsonk** [comment]
ping @lucacasonato when you get a moment...

**Review by lucacasonato — APPROVED** [review]
LGTM

**Pull request merged**
