### PR TITLE
Revert "chore: update to Deno 1.5.2"

### PR DESCRIPTION
**Pull request by lucacasonato**
Reverts denoland/deno_registry2#183

```

2020-11-22T00:43:22.276+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
-- | --
  | 2020-11-22T00:43:22.553+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:43:22.553+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:43:22.553+01:00 | ~~~~~
  | 2020-11-22T00:43:22.553+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:43:22.556+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:43:22.556+01:00 | Check the permission of the directory.
  | 2020-11-22T00:43:22.557+01:00 | error: bad deno executable
  | 2020-11-22T00:43:22.655+01:00 | START RequestId: 6bdaa3a1-db36-42f8-8ade-c501fcd33aae Version: $LATEST
  | 2020-11-22T00:43:22.862+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:43:24.004+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:43:24.004+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:43:24.004+01:00 | ~~~~~
  | 2020-11-22T00:43:24.004+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:43:24.042+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:43:24.042+01:00 | Check the permission of the directory.
  | 2020-11-22T00:43:24.082+01:00 | error: bad deno executable
  | 2020-11-22T00:43:24.223+01:00 | END RequestId: 6bdaa3a1-db36-42f8-8ade-c501fcd33aae
  | 2020-11-22T00:43:24.223+01:00 | REPORT RequestId: 6bdaa3a1-db36-42f8-8ade-c501fcd33aae Duration: 1567.47 ms Billed Duration: 1600 ms Memory Size: 128 MB Max Memory Used: 23 MB
  | 2020-11-22T00:43:24.223+01:00 | Unknown application error occurred Unhandled
  | 2020-11-22T00:43:25.029+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:43:25.273+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:43:25.273+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:43:25.273+01:00 | ~~~~~
  | 2020-11-22T00:43:25.273+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:43:25.277+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:43:25.277+01:00 | Check the permission of the directory.
  | 2020-11-22T00:43:25.277+01:00 | error: bad deno executable
  | 2020-11-22T00:47:03.669+01:00 | START RequestId: 3586dab2-bcd3-4a0c-bcdd-174a2b911451 Version: $LATEST
  | 2020-11-22T00:47:03.884+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:47:04.867+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:47:04.867+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:47:04.867+01:00 | ~~~~~
  | 2020-11-22T00:47:04.867+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:47:04.926+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:47:04.926+01:00 | Check the permission of the directory.
  | 2020-11-22T00:47:04.964+01:00 | error: bad deno executable
  | 2020-11-22T00:47:05.104+01:00 | END RequestId: 3586dab2-bcd3-4a0c-bcdd-174a2b911451
  | 2020-11-22T00:47:05.104+01:00 | REPORT RequestId: 3586dab2-bcd3-4a0c-bcdd-174a2b911451 Duration: 1433.34 ms Billed Duration: 1500 ms Memory Size: 128 MB Max Memory Used: 23 MB
  | 2020-11-22T00:47:05.104+01:00 | Unknown application error occurred Unhandled
  | 2020-11-22T00:47:05.462+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:47:05.701+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:47:05.701+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:47:05.701+01:00 | ~~~~~
  | 2020-11-22T00:47:05.701+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:47:05.707+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:47:05.707+01:00 | Check the permission of the directory.
  | 2020-11-22T00:47:05.707+01:00 | error: bad deno executable
  | 2020-11-22T00:47:06.172+01:00 | START RequestId: ca9a4802-6bef-46a1-abbf-46215463046b Version: $LATEST
  | 2020-11-22T00:47:06.364+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:47:07.385+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:47:07.385+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:47:07.385+01:00 | ~~~~~
  | 2020-11-22T00:47:07.385+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:47:07.424+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:47:07.424+01:00 | Check the permission of the directory.
  | 2020-11-22T00:47:07.444+01:00 | error: bad deno executable
  | 2020-11-22T00:47:07.584+01:00 | END RequestId: ca9a4802-6bef-46a1-abbf-46215463046b
  | 2020-11-22T00:47:07.584+01:00 | REPORT RequestId: ca9a4802-6bef-46a1-abbf-46215463046b Duration: 1410.12 ms Billed Duration: 1500 ms Memory Size: 128 MB Max Memory Used: 23 MB
  | 2020-11-22T00:47:07.584+01:00 | Unknown application error occurred Unhandled
  | 2020-11-22T00:47:15.385+01:00 | START RequestId: b9cc5cde-d427-4338-9116-a612f6aaae7f Version: $LATEST
  | 2020-11-22T00:47:15.624+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:47:18.908+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:47:18.908+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:47:18.908+01:00 | ~~~~~
  | 2020-11-22T00:47:18.908+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:47:18.987+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:47:18.987+01:00 | Check the permission of the directory.
  | 2020-11-22T00:47:19.024+01:00 | error: bad deno executable
  | 2020-11-22T00:47:19.164+01:00 | END RequestId: b9cc5cde-d427-4338-9116-a612f6aaae7f
  | 2020-11-22T00:47:19.164+01:00 | REPORT RequestId: b9cc5cde-d427-4338-9116-a612f6aaae7f Duration: 3777.15 ms Billed Duration: 3800 ms Memory Size: 128 MB Max Memory Used: 54 MB
  | 2020-11-22T00:47:19.164+01:00 | Unknown application error occurred Unhandled
  | 2020-11-22T00:47:19.356+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T00:47:19.695+01:00 | error: Uncaught SyntaxError: Unexpected reserved word
  | 2020-11-22T00:47:19.695+01:00 | await setup(DEFAULT_CONFIG);
  | 2020-11-22T00:47:19.695+01:00 | ~~~~~
  | 2020-11-22T00:47:19.695+01:00 | at <anonymous> (file:///var/task/bundle.js:3219:5)
  | 2020-11-22T00:47:19.698+01:00 | [0m[1m[31merror[0m: Could not create TypeScript compiler cache location: "/home/sbx_user1051/.cache/deno/gen"
  | 2020-11-22T00:47:19.698+01:00 | Check the permission of the directory.
  | 2020-11-22T00:47:19.699+01:00 | error: bad deno executable
```

cc @kitsonk:
1. bundle is not capable of bundling registry it seems. I will investigate what is causing it.
2. why do we try to create ts cache location when only running a bundle (only js, no ts)

### CODE REVIEW

**Comment by hayd** [comment]
I'm confused by the "bad deno executable" message... (that's printed when `deno eval 'Deno.version.deno'` fails).

**Comment by wperron** [comment]
We've had the "Bad deno executable" for a while now I think. @lucacasonato can you confirm with a log from 1.4.6? I can try to get one from my env tomorrow

**Comment by hayd** [comment]
@lucacasonato I think the "Could not create TypeScript compiler cache location" may also be a red-herring / a bug in the deno-lambda bootstrap (that we're not passing `DENO_DIR=/tmp/deno_dir` to `deno eval 'Deno.version.deno'` and that now apparently/surprisingly tries to create the cache location (without passing DENO_DIR it's `"/home/sbx_user1051/.cache/deno/`)!
I'll fix that in the al2 PR.

The SyntaxError looks legit though.

**Comment by lucacasonato** [comment]
1.4.6 log:
```


  | 2020-11-22T13:37:03.711+01:00 | warn: unable to import '.deno_dir/' as DENO_DIR
  | 2020-11-22T13:37:04.124+01:00 | INFO load deno plugin "deno_mongo" from local "/var/task/.deno_plugins/deno_mongo_a79a4be6f465f12a177649c69941b66b.so"
  | 2020-11-22T13:37:04.321+01:00 | START RequestId: f76a0bd8-d139-45e0-8b9d-d191edee6c90 Version: $LATEST
  | 2020-11-22T13:37:05.920+01:00 | END RequestId: f76a0bd8-d139-45e0-8b9d-d191edee6c90
  | 2020-11-22T13:37:05.920+01:00 | REPORT RequestId: f76a0bd8-d139-45e0-8b9d-d191edee6c90 Duration: 1598.67 ms Billed Duration: 2300 ms Memory Size: 128 MB Max Memory Used: 100 MB Init Duration: 632.51 ms
  | 2020-11-22T13:37:10.796+01:00 | START RequestId: 66cbb299-04ff-4cb3-a33d-8b536a6466b2 Version: $LATEST
  | 2020-11-22T13:37:10.834+01:00 | END RequestId: 66cbb299-04ff-4cb3-a33d-8b536a6466b2
  | 2020-11-22T13:37:10.834+01:00 | REPORT RequestId: 66cbb299-04ff-4cb3-a33d-8b536a6466b2 Duration: 35.44 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 100 MB
  | 2020-11-22T13:39:51.478+01:00 | START RequestId: 549e5658-5080-4fa1-9b3c-19419334f735 Version: $LATEST
  | 2020-11-22T13:39:51.500+01:00 | END RequestId: 549e5658-5080-4fa1-9b3c-19419334f735
  | 2020-11-22T13:39:51.500+01:00 | REPORT RequestId: 549e5658-5080-4fa1-9b3c-19419334f735 Duration: 19.17 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 100 MB
 



```

**Pull request merged**
