### PR TITLE
feat: use repo ID to identify modules

### LINKED ISSUE #24: Use GitHub repo ID to identify repos
Currently we use `owner/repository`. This would solve the repo name change issue.

### PR DESCRIPTION
**Pull request by wperron**
Fixes #24

### CODE REVIEW

**Comment by wperron** [comment]
Migration script available as a gist [here](https://gist.github.com/wperron/7d777b9120f0e21ccd6b5b5b33d03b88)

**Comment by wperron** [comment]
I formatted using a nightly build of deno, that's why there's so many changes in import statements, I can remove them from the PR if needed

**Review by lucacasonato — APPROVED** [review]
LGTM - thanks :-)

**Comment by lucacasonato** [comment]
Finished the migration without issues.

**Pull request merged**
