### PR TITLE
feat: GET /module?query=<name>

### PR DESCRIPTION
**Pull request by divy-work**

### CODE REVIEW

**Comment by lucacasonato** [comment]
@divy-work Can you get the information you want from https://cdn.deno.land/MODULENAME/meta/versions.json or https://cdn.deno.land/MODULENAME/versions/VERSION/meta/meta.json? I am not very keen on adding a new API endpoint ATM.

**Comment by divy-work** [comment]
No worries! It would have been great to have an endpoint in the API itself.

**Comment by divy-work** [comment]
A major use case are package/deps managers like Trex / Hatcher. Who can get information about the module from the API

**Comment by lucacasonato** [comment]
> A major use case are package/deps managers like Trex / Hatcher. Who can get information about the module from the API

I think they can get the info they need from https://cdn.deno.land/MODULENAME/meta/versions.json right? The data stored in the database is pretty much the same as https://cdn.deno.land/MODULENAME/versions/VERSION/meta/meta.json with the version being the latest version. I don't see how this provides any benefit. This makes a request t o our database rather than doing a cheap and highly cacheable call to S3.

**Pull request closed without merging**
